"""
Constants used across the offerClick backend application.
Centralizes magic strings and common values for easier maintenance.
"""

# Job Sources
SOURCE_MANUAL = "Manual"
SOURCE_MANUAL_SIMPLE = "Manual-Simple"
SOURCE_LINKEDIN = "LinkedIn"
SOURCE_INDEED = "Indeed"
SOURCE_UNKNOWN = "Unknown"

# Search Metadata for Manual Jobs
SEARCH_TERM_MANUAL = "Manual Add"
SEARCH_TERM_MANUAL_SIMPLE = "Manual Add (Simple)"
SEARCH_CITY_MANUAL = "Manual Add"
SEARCH_CITY_MANUAL_SIMPLE = "Manual Add (Simple)"

# Default Values for Missing Data
DEFAULT_VALUE_NA = "N/A"
DEFAULT_COMPANY = "Unknown Company"
DEFAULT_ROLE = "Unknown Role"
DEFAULT_LOCATION = "Unknown"

# Screening Results
SCREENING_ACCEPT = "ACCEPT"
SCREENING_REJECT = "REJECT"
SCREENING_SENIOR = "SENIOR"
SCREENING_NOT_SENIOR = "NOT_SENIOR"
SCREENING_UNKNOWN = "UNKNOWN"

# Match Ratings
MATCH_STRONG = "STRONG MATCH"
MATCH_MEDIUM = "MEDIUM MATCH"
MATCH_WEAK = "WEAK MATCH"

# CSV Column Names (Standardized UPPERCASE)
COL_TITLE = "TITLE"
COL_COMPANY = "COMPANY"
COL_LOCATION = "LOCATION"
COL_IS_REMOTE = "IS_REMOTE"
COL_JOB_URL = "JOB_URL"
COL_SOURCE = "SOURCE"
COL_SEARCH_TERM = "SEARCH_TERM"
COL_SEARCH_CITY = "SEARCH_CITY"

COL_TECHNICAL_STACK = "TECHNICAL_STACK"
COL_KEY_RESPONSIBILITIES = "KEY_RESPONSIBILITIES"
COL_REQUIRED_EXPERIENCE = "REQUIRED_EXPERIENCE"
COL_SUCCESS_METRICS = "SUCCESS_METRICS"
COL_SALARY_RANGE = "SALARY_RANGE"
COL_SALARY_IS_ESTIMATED = "SALARY_IS_ESTIMATED"

COL_SYSTEMS_FIT = "SYSTEMS_FIT"
COL_RETRIEVAL_INFRA_FIT = "RETRIEVAL_INFRA_FIT"
COL_ALGORITHMIC_ML_FIT = "ALGORITHMIC_ML_FIT"
COL_OVERALL_MATCH = "OVERALL_MATCH"
COL_MATCH_REASON = "MATCH_REASON"
COL_VISA_ANALYSIS = "VISA_ANALYSIS"

# Repository Cache Settings
CACHE_TTL_SECONDS = 3  # Cache time-to-live in seconds
